// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmIe-UuhXXkSRqdOicK96oOqavhs-oX8c',
    appId: '1:659391367327:web:d5bef03ac6d3aa706f3aaa',
    messagingSenderId: '659391367327',
    projectId: 'resume-builder-53e3d',
    authDomain: 'resume-builder-53e3d.firebaseapp.com',
    storageBucket: 'resume-builder-53e3d.firebasestorage.app',
    measurementId: 'G-8KX498VR1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATWfNMrlQINUc47HkBCVGa6kRk0muHdPk',
    appId: '1:659391367327:android:3e47fba79aa47e636f3aaa',
    messagingSenderId: '659391367327',
    projectId: 'resume-builder-53e3d',
    storageBucket: 'resume-builder-53e3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuc5xp2gmCVrwaLrIuoUubDSUKgZ-oZqw',
    appId: '1:659391367327:ios:a5945a71ca88e4e36f3aaa',
    messagingSenderId: '659391367327',
    projectId: 'resume-builder-53e3d',
    storageBucket: 'resume-builder-53e3d.firebasestorage.app',
    iosBundleId: 'com.example.resumeBuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuc5xp2gmCVrwaLrIuoUubDSUKgZ-oZqw',
    appId: '1:659391367327:ios:a5945a71ca88e4e36f3aaa',
    messagingSenderId: '659391367327',
    projectId: 'resume-builder-53e3d',
    storageBucket: 'resume-builder-53e3d.firebasestorage.app',
    iosBundleId: 'com.example.resumeBuilder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmIe-UuhXXkSRqdOicK96oOqavhs-oX8c',
    appId: '1:659391367327:web:b20cfec568631b086f3aaa',
    messagingSenderId: '659391367327',
    projectId: 'resume-builder-53e3d',
    authDomain: 'resume-builder-53e3d.firebaseapp.com',
    storageBucket: 'resume-builder-53e3d.firebasestorage.app',
    measurementId: 'G-XHY2KV51NW',
  );
}
